# -*- coding: utf-8 -*-
"""10app_imc_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzR2sOEfFwe4hFsaJWPYTS7fFN-PG15L
"""

import streamlit as st
import pandas as pd
import plotly.express as px # <-- Esta é a linha que estava causando o erro no deploy
# from datetime import datetime # Não é estritamente necessário para o uso atual, mas se for usar outras funções, pode manter

class CalculadoraIMC:
    def __init__(self):
        # A nova estrutura de classificações é excelente!
        self.classificacoes = [
            {"max": 18.4, "cat": "Abaixo do peso", "desc": "Indicado buscar orientação para ganho de peso saudável.", "cor": "warning"},
            {"max": 24.9, "cat": "Peso normal", "desc": "Seu peso está saudável. Mantenha hábitos equilibrados.", "cor": "success"},
            {"max": 29.9, "cat": "Sobrepeso", "desc": "Recomenda-se orientação para plano de emagrecimento.", "cor": "warning"},
            {"max": 34.9, "cat": "Obesidade Grau I", "desc": "Acompanhamento profissional importante.", "cor": "danger"},
            {"max": 39.9, "cat": "Obesidade Grau II", "desc": "Risco elevado. Procure ajuda urgente.", "cor": "danger"},
            {"max": float('inf'), "cat": "Obesidade Grau III", "desc": "Risco muito elevado. Tratamento rigoroso.", "cor": "danger"}
        ]

    def calcular_imc(self, peso, altura):
        if altura <= 0 or peso <= 0:
            raise ValueError("Valores devem ser positivos.")
        return peso / (altura ** 2)

    def classificar_imc(self, imc):
        for classe in self.classificacoes:
            if imc <= classe["max"]:
                return (classe["cat"], classe["desc"], classe["cor"])
        # Caso o IMC seja maior que todas as categorias definidas (o que não deve acontecer com float('inf'))
        return self.classificacoes[-1]['cat'], self.classificacoes[-1]['desc'], self.classificacoes[-1]['cor']

    # Nome do método padronizado para "obter_dicas"
    def obter_dicas(self, classificacao, idade):
        dicas = [
            "### 📌 Dicas Gerais para uma Alimentação Saudável",
            "- **Priorize alimentos in natura ou minimamente processados:** Frutas, verduras, legumes, grãos inteiros, carnes magras, ovos.",
            "- **Evite alimentos ultraprocessados:** Refrigerantes, biscoitos recheados, salgadinhos, embutidos - ricos em açúcar, sódio e gorduras não saudáveis.",
            "- **Cozinhe seus próprios alimentos:** Controle os ingredientes e qualidade das preparações.",
            "- **Faça refeições conscientes:** Coma devagar, em ambiente tranquilo e preferencialmente em companhia.",
            "- **Hidrate-se adequadamente:** Beba água ao longo do dia (6-8 copos diários).",
            "- **Use óleos, sal e açúcar com moderação:** Prefira versões naturais e evite excessos.",
            "- **Mantenha-se ativo:** Combine alimentação saudável com atividade física regular.",
            "- **Varie os alimentos:** Consuma diferentes grupos alimentares ao longo da semana.",
            "- **Atenção aos rótulos:** Leia as informações nutricionais dos produtos industrializados."
        ]

        if "Abaixo do peso" in classificacao:
            dicas.extend([
                "\n### 🥑 Estratégias para Ganho de Peso Saudável - Recomendações Médicas de Preferência:",
                "- Consuma alimentos ricos em nutrientes e calorias saudáveis: abacate, azeite, castanhas",
                "- Faça 6 refeições diárias em porções menores",
                "- Inclua proteínas em todas as refeições principais",
                "- Consulte um nutricionista para plano individualizado"
            ])
        elif "Sobrepeso" in classificacao or "Obesidade" in classificacao:
            dicas.extend([
                "\n### 🥦 Estratégias para Emagrecimento Saudável - Recomendações Médicas de Preferência:",
                "- Aumente o consumo de fibras: vegetais folhosos, frutas com casca, grãos integrais",
                "- Consuma proteínas magras: peixes, frango, ovos, leguminosas",
                "- Reduza o consumo de bebidas alcoólicas",
                "- Consulte um nutricionista para plano individualizado",
                "- Reduza gradualmente o consumo de açúcares e gorduras saturadas",
                "- Mantenha regularidade nas refeições para evitar compulsões",
                "- Importante nesse processo - Pratique atividade física regular com orientação profissional"
            ])
        elif "Peso normal" in classificacao:
            dicas.extend([
                "\n### ✅ Mantenha seus Hábitos Saudáveis:",
                "- Continue com a rotina alimentar equilibrada",
                "- Monitore seu peso periodicamente",
                "- Experimente novas receitas saudáveis",
                "- Importante nesse processo - Mantenha check-ups regulares"
            ])

        if idade < 18:
            dicas.extend([
                f"\n### 👧 Considerações para {idade} anos:",
                "- Fundamental papel da família na oferta de alimentos saudáveis",
                "- Evite açúcar para menores de 2 anos e modere para maiores",
                "- Priorize lanches naturais: frutas, sanduíches integrais",
                "- Mantenha horários regulares para as refeições"
            ])
        elif idade >= 60:
            dicas.extend([
                f"\n### 👵 Considerações para {idade} anos:",
                "- Aumente consumo de proteínas para manter massa muscular",
                "- Atenção à hidratação (a sede pode diminuir com a idade)",
                "- Consuma alimentos ricos em cálcio e vitamina D",
                "- Adapte textura dos alimentos se necessário"
            ])

        return "\n".join(dicas)

    # Nome do método padronizado para "obter_resumos"
    def obter_resumos(self):
        return """
        ## 📚 Referências Científicas

        ### Guias Oficiais:
        1. [Guia Alimentar para a População Brasileira](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_populacao_brasileira_2ed.pdf)
        2. [Guia para Crianças Menores de 2 Anos](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_crianca_brasileira_versao_resumida.pdf)

        ### Estudos Relevantes:
        3. [Alimentação Saudável](https://bvsms.saude.gov.br/bvs/publicacoes/alimentacao_saudavel.pdf)
        4. [Clínica Einstein: Dietas & Emagrecimento](https://vidasaudavel.einstein.br/wp-content/uploads/2021/02/98.-Dietas-Emagrecimento.pdf)
        """

# Configuração da Página
st.set_page_config(
    page_title="Orientações básicas",
    page_icon="🥗",
    layout="wide", # Usando layout wide para melhor visualização do gráfico e dicas
    initial_sidebar_state="expanded"
)

# Interface Principal
st.title("🥗 Calculadora de IMC")
st.markdown("""
    *Calculadora de IMC com orientações baseadas em evidências científicas:*
""")

# Entradas do Usuário dentro de um formulário
with st.form(key='form_imc'):
    col1, col2, col3 = st.columns(3)
    with col1:
        peso = st.number_input("Peso (kg):", min_value=30.0, max_value=300.0, step=0.1, value=None, format="%.1f") # Definir value=None para começar vazio
    with col2:
        altura = st.number_input("Altura (m):", min_value=1.0, max_value=2.5, step=0.01, value=None, format="%.2f") # Definir value=None para começar vazio
    with col3:
        idade = st.number_input("Idade (anos):", min_value=2, max_value=120, step=1, value=None) # Definir value=None para começar vazio

    # Botão de submit do formulário
    if st.form_submit_button("Calcular IMC e Obter Orientações", type="primary"):
        try:
            # Verifica se todos os campos foram preenchidos
            if not all([peso, altura, idade]):
                st.error("Preencha todos os campos!")
            else:
                calc = CalculadoraIMC()
                imc = calc.calcular_imc(peso, altura)
                classificacao, descricao, cor = calc.classificar_imc(imc)

                st.success("Análise Completa Realizada!")

                # Exibição dos resultados e dicas em colunas
                with st.container():
                    col_res1, col_res2 = st.columns([1, 2])

                    with col_res1:
                        st.metric("IMC Calculado", f"{imc:.1f}")
                        st.markdown(f"""
                            **Classificação:**
                            :{cor}[**{classificacao}**]
                            _{descricao}_
                        """)

                        # Gráfico Plotly
                        # Cria um DataFrame para o gráfico (opcional, mas bom para plotly)
                        df_imc = pd.DataFrame({'Categoria': ['Seu IMC'], 'Valor': [imc]})

                        fig = px.bar(df_imc, x="Categoria", y="Valor",
                                     title="Posição nas Faixas de IMC",
                                     labels={"Valor": "Valor do IMC"},
                                     color_discrete_sequence=["#27ae60"], # Cor base para o seu IMC
                                     range_y=[0, 45]) # Ajusta o range para melhor visualização

                        # Adiciona as faixas de IMC como retângulos no gráfico
                        fig.add_hrect(y0=18.5, y1=24.9, fillcolor="#2ecc71", opacity=0.2, annotation_text="Normal", annotation_position="top left")
                        fig.add_hrect(y0=25, y1=29.9, fillcolor="#f1c40f", opacity=0.2, annotation_text="Sobrepeso", annotation_position="top left")
                        fig.add_hrect(y0=30, y1=34.9, fillcolor="#e67e22", opacity=0.2, annotation_text="Obesidade I", annotation_position="top left")
                        fig.add_hrect(y0=35, y1=39.9, fillcolor="#d35400", opacity=0.2, annotation_text="Obesidade II", annotation_position="top left")
                        fig.add_hrect(y0=40, y1=float('inf'), fillcolor="#c0392b", opacity=0.2, annotation_text="Obesidade III", annotation_position="top left")
                        fig.add_hrect(y0=0, y1=18.4, fillcolor="#3498db", opacity=0.2, annotation_text="Abaixo do Peso", annotation_position="top left")


                        st.plotly_chart(fig, use_container_width=True)

                    with col_res2:
                        st.markdown(calc.obter_dicas(classificacao, idade))

                        with st.expander("🔍 Referências Científicas", expanded=True):
                            st.markdown(calc.obter_resumos())

        except Exception as e:
            st.error(f"Erro: {str(e)}")

# Rodapé
st.markdown("---")
st.markdown("""
    **Desenvolvido por:** Marcia Romanato
""")