# -*- coding: utf-8 -*-
"""11teste_imc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2HZiYRL1dTZnY99C2SZarOgwexnnbra
"""

import streamlit as st
import pandas as pd # <-- Esta biblioteca precisa ser listada em requirements.txt

# --- Classe CalculadoraIMC ---
class CalculadoraIMC:
    def __init__(self):
        pass

    def calcular_imc(self, peso, altura):
        """
        Calcula o Índice de Massa Corporal (IMC).
        Args:
            peso (float): Peso em quilogramas (kg).
            altura (float): Altura em metros (m).
        Returns:
            float: O valor do IMC.
        Raises:
            ValueError: Se peso ou altura forem zero ou negativos.
        """
        if altura <= 0 or peso <= 0:
            raise ValueError("Peso e altura devem ser valores positivos.")
        return peso / (altura ** 2)

    def classificar_imc(self, imc):
        """
        Classifica o IMC de acordo com a tabela da OMS.
        Args:
            imc (float): O valor do IMC.
        Returns:
            tuple: Uma tupla contendo a classificação do IMC e uma breve descrição.
        """
        if imc < 18.5:
            return "Abaixo do peso", "Indicado buscar orientação para ganho de peso saudável.", "warning"
        elif 18.5 <= imc <= 24.9:
            return "Peso normal", "Seu peso está saudável. Mantenha hábitos alimentares equilibrados e atividade física.", "success"
        elif 25 <= imc <= 29.9:
            return "Sobrepeso", "Recomenda-se buscar orientação para um plano de emagrecimento saudável.", "warning"
        elif 30 <= imc <= 34.9:
            return "Obesidade Grau I", "Importante buscar acompanhamento profissional para um plano de emagrecimento e melhora da saúde.", "danger"
        elif 35 <= imc <= 39.9:
            return "Obesidade Grau II", "Risco elevado. Procure acompanhamento médico e nutricional urgente para um plano de emagrecimento.", "danger"
        else:
            return "Obesidade Grau III (Mórbida)", "Risco muito elevado. É fundamental buscar acompanhamento médico e nutricional para um plano de tratamento rigoroso.", "danger"

    def obter_dicas_dieta(self, classificacao_imc, idade):
        """
        Fornece dicas de dieta baseadas na classificação do IMC e na idade.
        As dicas são baseadas nos arquivos PDF fornecidos.
        """
        dicas = []

        dicas.append("### Dicas Gerais para uma Alimentação Saudável")
        dicas.append("- Priorize alimentos *in natura* ou minimamente processados (frutas, verduras, legumes, grãos inteiros, carnes magras, ovos).")
        dicas.append("- Evite alimentos **ultraprocessados** (refrigerantes, biscoitos recheados, salgadinhos, embutidos) pois são ricos em açúcar, sódio e gorduras não saudáveis.")
        dicas.append("- Cozinhe seus próprios alimentos sempre que possível. Isso ajuda a controlar os ingredientes.")
        dicas.append("- Faça das refeições momentos de prazer e atenção, comendo devagar e em companhia, se possível.")
        dicas.append("- Beba bastante água ao longo do dia. A água é essencial para diversas funções do corpo.")
        dicas.append("- Consuma óleos, sal e açúcar em pequenas quantidades, preferindo versões naturais e evitando o excesso.")
        dicas.append("- Seja ativo! A combinação de alimentação saudável e atividade física é fundamental para a saúde.")

        if "Abaixo do peso" in classificacao_imc:
            dicas.append("\n### Para 'Abaixo do peso':")
            dicas.append("- Busque um nutricionista para um plano de ganho de peso saudável, focado em nutrientes e não apenas calorias vazias.")
            dicas.append("- Aumente o consumo de alimentos ricos em energia e nutrientes, como abacate, azeite, castanhas e sementes.")
            dicas.append("- Faça refeições menores e mais frequentes ao longo do dia.")
        elif "Sobrepeso" in classificacao_imc or "Obesidade" in classificacao_imc:
            dicas.append("\n### Para 'Sobrepeso' ou 'Obesidade':")
            dicas.append("- O foco é a reeducação alimentar. Elimine ou reduza drasticamente alimentos ultraprocessados.")
            dicas.append("- Aumente o consumo de fibras (presentes em frutas, vegetais, grãos integrais, leguminosas) para aumentar a saciedade.")
            dicas.append("- Invista em alimentos que desincham e têm ação anti-inflamatória, como aqueles ricos em ômega-3 (salmão, sardinha, linhaça).")
            dicas.append("- Consulte um profissional para um plano alimentar individualizado e orientação sobre atividade física adequada.")
            dicas.append("- Evite dietas muito restritivas, que podem levar ao efeito sanfona.")
        elif "Peso normal" in classificacao_imc:
            dicas.append("\n### Para 'Peso normal':")
            dicas.append("- Continue com uma alimentação equilibrada, variada e colorida.")
            dicas.append("- Mantenha a ingestão de água adequada e a prática regular de atividade física.")
            dicas.append("- Fique atento aos sinais de fome e saciedade do seu corpo.")

        if idade < 18:
            dicas.append(f"\n### Considerações para sua idade ({idade} anos):")
            dicas.append("- Para crianças e adolescentes, é crucial o papel da família na oferta de alimentos saudáveis e no exemplo.")
            dicas.append("- Evitar açúcar e produtos açucarados para crianças menores de 3 anos é fundamental. Para os mais velhos, moderar o consumo.")
            dicas.append("- Priorize a alimentação em família, em um ambiente prazeroso e sem distrações como TV/celular.")
        elif idade >= 60:
            dicas.append(f"\n### Considerações para sua idade ({idade} anos):")
            dicas.append("- Para idosos, a alimentação deve ser rica em nutrientes para manter a massa muscular e óssea.")
            dicas.append("- Atenção à hidratação, pois a sensação de sede pode diminuir com a idade.")
            dicas.append("- Pode ser necessário um acompanhamento nutricional para adequar a dieta a possíveis condições de saúde.")

        return "\n".join(dicas)

    def obter_resumos_importantes(self):
        """
        Retorna resumos de assuntos importantes dos arquivos em anexo, com referências e links.
        """
        return """
## Resumos de Assuntos Importantes e Referências

### 1. Alimentação Saudável e Guias Alimentares:
- O [Guia Alimentar para a População Brasileira (2ª edição)](https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/publicacoes-saude-brasil/guia-alimentar-para-a-populacao-brasileira/view) é uma referência fundamental. Ele divide os alimentos em categorias baseadas no grau de processamento (in natura, minimamente processados, processados e ultraprocessados) e enfatiza a base alimentar em produtos naturais.
- A regra de ouro é "coma alimentos de verdade", ou seja, aqueles encontrados na natureza ou que passaram por mínimas alterações.
- **Referência:** Brasil. Ministério da Saúde. Secretaria de Atenção à Saúde. Departamento de Atenção Básica. **Guia alimentar para a população brasileira**. 2. ed. Brasília: Ministério da Saúde, 2014.

### 2. Emagrecimento Saudável:
- O emagrecimento sustentável é um processo que envolve mudança de hábitos e não apenas dietas restritivas.
- Aumentar a sensação de saciedade com fibras (frutas, vegetais, grãos integrais, leguminosas) e proteínas magras é uma estratégia eficaz.
- Alimentos com propriedades termogênicas e anti-inflamatórias (chá de hibisco, pimentas, gengibre, alimentos ricos em ômega-3) podem auxiliar, mas não são soluções milagrosas.
- **Referência:** Conteúdo extraído do arquivo `ebook-emagrecimento.pdf`, que aborda o processo de emagrecimento de forma saudável e sustentável.

### 3. Importância da Água e Fibras:
- A água é crucial para hidratação, transporte de nutrientes e funcionamento dos órgãos. Recomenda-se ingestão adequada ao longo do dia.
- As fibras alimentares promovem a saúde intestinal, ajudam no controle do colesterol e da glicemia, e contribuem para a saciedade.
- **Referência:** Informações baseadas nos arquivos `manual_de_nutricao.pdf` e `alimentacao_saudavel.pdf`, que detalham a importância desses componentes.

### 4. Cuidados com Ultraprocessados:
- Alimentos ultraprocessados são formulados para serem muito palatáveis e muitas vezes levam ao consumo excessivo.
- São associados a maior risco de obesidade, doenças cardíacas, diabetes e outros problemas de saúde.
- **Referência:** Amplamente discutido no [Guia Alimentar para a População Brasileira](https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/publicacoes-saude-brasil/guia-alimentar-para-a-populacao-brasileira/view) e nos materiais `manual_de_nutricao.pdf` e `alimentacao_saudavel.pdf`.

### 5. Alimentação em Diferentes Fases da Vida:
- Crianças e adolescentes necessitam de uma alimentação balanceada para crescimento e desenvolvimento. A família tem um papel vital.
- Idosos devem ter atenção especial à densidade nutricional dos alimentos para manter a massa muscular e óssea.
- **Referência:** Conteúdo adaptado do `EBOOK ALIMENTAÇÃO SAUDÁVEL.pdf` (foco em crianças) e `alimentacao_saudavel.pdf` (aborda diversas faixas etárias, incluindo idosos). Para crianças menores de 2 anos, consulte também o [Guia Alimentar para Crianças Brasileiras menores de 2 anos](https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/publicacoes-saude-brasil/2019/guia-alimentar-para-criancas-brasileiras-menores-de-2-anos).
        """

# --- Configuração da Aplicação Streamlit ---

st.set_page_config(
    page_title="Calculadora de IMC e Dicas de Saúde",
    page_icon="🍎",
    layout="centered"
)

st.title("🍎 Calculadora de IMC e Dicas de Saúde")
st.markdown("Calcule seu Índice de Massa Corporal (IMC) e receba dicas personalizadas de alimentação e saúde.")

# Inicializa a calculadora
calculadora = CalculadoraIMC()

# Usamos um estado de sessão para controlar se já calculamos o IMC
# Isso permite que os resultados e o botão "Novo Cálculo" só apareçam após o primeiro cálculo.
if 'calculado' not in st.session_state:
    st.session_state.calculado = False

# --- Entradas do Usuário ---
st.header("Seus Dados")

col1, col2, col3 = st.columns(3)

with col1:
    # Campos vazios, sem valor padrão (value=None), para forçar a entrada do usuário.
    # Adicionado 'help' para guiar o usuário no preenchimento.
    peso = st.number_input("Peso (kg):", min_value=1.0, max_value=300.0, value=None, step=0.1, format="%.1f", key="peso_input", help="Insira seu peso em quilogramas (ex: 70.5)")
with col2:
    altura = st.number_input("Altura (m):", min_value=0.50, max_value=2.50, value=None, step=0.01, format="%.2f", key="altura_input", help="Insira sua altura em metros (ex: 1.75)")
with col3:
    idade = st.number_input("Idade (anos):", min_value=1, max_value=120, value=None, step=1, key="idade_input", help="Insira sua idade em anos")

# Botão para calcular
if st.button("Calcular IMC", key="calcular_button"):
    # Verifica se todos os campos foram preenchidos antes de tentar calcular
    if peso is None or altura is None or idade is None:
        st.warning("Por favor, preencha todos os campos (peso, altura e idade) para calcular o IMC.")
    else:
        try:
            imc = calculadora.calcular_imc(peso, altura)
            classificacao, descricao, cor = calculadora.classificar_imc(imc)

            st.session_state.calculado = True # Marca que o cálculo foi feito com sucesso

            st.subheader("Seu Resultado:")
            st.write(f"Seu IMC é: **{imc:.2f}**")

            # Exibe a classificação com cor e ícone apropriados
            if cor == "success":
                st.success(f"**Classificação:** {classificacao}")
            elif cor == "warning":
                st.warning(f"**Classificação:** {classificacao}")
            else: # Cor "danger"
                st.error(f"**Classificação:** {classificacao}")

            st.info(f"**Observação:** {descricao}")

            st.markdown("---") # Linha divisória

            # --- Dicas de Dieta ---
            st.subheader("Dicas de Dieta e Saúde")
            dicas = calculadora.obter_dicas_dieta(classificacao, idade)
            st.markdown(dicas)

            st.markdown("---") # Linha divisória

            # --- Resumos Importantes ---
            resumos = calculadora.obter_resumos_importantes()
            st.markdown(resumos)

        except ValueError as e:
            st.error(f"Erro: {e}")
        except Exception as e:
            st.error(f"Ocorreu um erro inesperado: {e}")

# --- Botão "Novo Cálculo" ---
# Este botão só aparece depois que o cálculo inicial é feito (st.session_state.calculado é True)
if st.session_state.calculado:
    st.markdown("---")
    # Este botão recarrega a aplicação do zero, limpando todos os campos e saídas.
    # É a forma mais eficaz de "reiniciar" a UI no Streamlit.
    if st.button("Novo Cálculo de IMC", key="novo_calculo_button"):
        st.session_state.calculado = False # Reseta o estado para que o app volte ao início
        st.experimental_rerun() # Força a recarga completa do script

st.markdown("---")
st.markdown("Criado com ❤️ e dados de materiais de nutrição e saúde pública.")
st.markdown("Lembre-se: este é um aplicativo informativo. Sempre consulte um profissional de saúde para orientações personalizadas.")