# -*- coding: utf-8 -*-
"""22app_imc_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gjzTWTfT2Y0x2T3lamXqK8W7qXEfKoVW
"""

import streamlit as st
import pandas as pd
# import plotly.express as px # REMOVIDO: Esta linha causava o ModuleNotFoundError
# from datetime import datetime # REMOVIDO: Esta importação não é utilizada no código atual

class CalculadoraIMC:
    def __init__(self):
        self.classificacoes = [
            {"max": 18.4, "cat": "Abaixo do peso", "desc": "Indicado buscar orientação para ganho de peso saudável.", "cor": "warning"},
            {"max": 24.9, "cat": "Peso normal", "desc": "Seu peso está saudável. Mantenha hábitos equilibrados.", "cor": "success"},
            {"max": 29.9, "cat": "Sobrepeso", "desc": "Recomenda-se orientação para plano de emagrecimento.", "cor": "warning"},
            {"max": 34.9, "cat": "Obesidade Grau I", "desc": "Acompanhamento profissional importante.", "cor": "danger"},
            {"max": 39.9, "cat": "Obesidade Grau II", "desc": "Risco elevado. Procure ajuda urgente.", "cor": "danger"},
            {"max": float('inf'), "cat": "Obesidade Grau III", "desc": "Risco muito elevado. Tratamento rigoroso.", "cor": "danger"}
        ]

    def calcular_imc(self, peso, altura):
        if altura <= 0 or peso <= 0:
            raise ValueError("Valores devem ser positivos.")
        return peso / (altura ** 2)

    def classificar_imc(self, imc):
        for classe in self.classificacoes:
            if imc <= classe["max"]:
                return (classe["cat"], classe["desc"], classe["cor"])
        return self.classificacoes[-1]['cat'], self.classificacoes[-1]['desc'], self.classificacoes[-1]['cor']

    def obter_dicas(self, classificacao, idade):
        dicas = [
            "### 📌 Dicas Gerais para uma Alimentação Saudável",
            "- **Priorize alimentos in natura ou minimamente processados:** Frutas, verduras, legumes, grãos inteiros, carnes magras, ovos.",
            "- **Evite alimentos ultraprocessados:** Refrigerantes, biscoitos recheados, salgadinhos, embutidos - ricos em açúcar, sódio e gorduras não saudáveis.",
            "- **Cozinhe seus próprios alimentos:** Controle os ingredientes e qualidade das preparações.",
            "- **Faça refeições conscientes:** Coma devagar, em ambiente tranquilo e preferencialmente em companhia.",
            "- **Hidrate-se adequadamente:** Beba água ao longo do dia (6-8 copos diários).",
            "- **Use óleos, sal e açúcar com moderação:** Prefira versões naturais e evite excessos.",
            "- **Mantenha-se ativo:** Combine alimentação saudável com atividade física regular.",
            "- **Varie os alimentos:** Consuma diferentes grupos alimentares ao longo da semana.",
            "- **Atenção aos rótulos:** Leia as informações nutricionais dos produtos industrializados."
        ]

        if "Abaixo do peso" in classificacao:
            dicas.extend([
                "\n### 🥑 Estratégias para Ganho de Peso Saudável - Recomendações Médicas de Preferência:",
                "- Consuma alimentos ricos em nutrientes e calorias saudáveis: abacate, azeite, castanhas",
                "- Faça 6 refeições diárias em porções menores",
                "- Inclua proteínas em todas as refeições principais",
                "- Consulte um nutricionista para plano individualizado"
            ])
        elif "Sobrepeso" in classificacao or "Obesidade" in classificacao:
            dicas.extend([
                "\n### 🥦 Estratégias para Emagrecimento Saudável - Recomendações Médicas de Preferência:",
                "- Aumente o consumo de fibras: vegetais folhosos, frutas com casca, grãos integrais",
                "- Consuma proteínas magras: peixes, frango, ovos, leguminosas",
                "- Reduza o consumo de bebidas alcoólicas",
                "- Consulte um nutricionista para plano individualizado",
                "- Reduza gradualmente o consumo de açúcares e gorduras saturadas",
                "- Mantenha regularidade nas refeições para evitar compulsões",
                "- Importante nesse processo - Pratique atividade física regular com orientação profissional"
            ])
        elif "Peso normal" in classificacao:
            dicas.extend([
                "\n### ✅ Mantenha seus Hábitos Saudáveis:",
                "- Continue com a rotina alimentar equilibrada",
                "- Monitore seu peso periodicamente",
                "- Experimente novas receitas saudáveis",
                "- Importante nesse processo - Mantenha check-ups regulares"
            ])

        if idade < 18:
            dicas.extend([
                f"\n### 👧 Considerações para {idade} anos:",
                "- Fundamental papel da família na oferta de alimentos saudáveis",
                "- Evite açúcar para menores de 2 anos e modere para maiores",
                "- Priorize lanches naturais: frutas, sanduíches integrais",
                "- Mantenha horários regulares para as refeições"
            ])
        elif idade >= 60:
            dicas.extend([
                f"\n### 👵 Considerações para {idade} anos:",
                "- Aumente consumo de proteínas para manter massa muscular",
                "- Atenção à hidratação (a sede pode diminuir com a idade)",
                "- Consuma alimentos ricos em cálcio e vitamina D",
                "- Adapte textura dos alimentos se necessário"
            ])

        return "\n".join(dicas)

    def obter_resumos(self):
        return """
        ## 📚 Referências Científicas

        ### Guias Oficiais:
        1. [Guia Alimentar para a População Brasileira](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_populacao_brasileira_2ed.pdf)
        2. [Guia para Crianças Menores de 2 Anos](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_crianca_brasileira_versao_resumida.pdf)

        ### Estudos Relevantes:
        3. [Alimentação Saudável](https://bvsms.saude.gov.br/bvs/publicacoes/alimentacao_saudavel.pdf)
        4. [Clínica Einstein: Dietas & Emagrecimento](https://vidasaudavel.einstein.br/wp-content/uploads/2021/02/98.-Dietas-Emagrecimento.pdf)
        """

# Configuração da Página
st.set_page_config(
    page_title="Orientações básicas",
    page_icon="🥗",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Interface Principal
st.title("🥗 Calculadora de IMC")
st.markdown("""
    *Calculadora de IMC com orientações baseadas em evidências científicas:*
""")

# Inicializa a calculadora
calc = CalculadoraIMC()

# Usamos um estado de sessão para controlar se já calculamos o IMC
if 'calculado' not in st.session_state:
    st.session_state.calculado = False

# Entradas do Usuário dentro de um formulário
with st.form(key='form_imc'):
    col1, col2, col3 = st.columns(3)
    with col1:
        peso = st.number_input("Peso (kg):", min_value=30.0, max_value=300.0, step=0.1, value=None, format="%.1f")
    with col2:
        altura = st.number_input("Altura (m):", min_value=1.0, max_value=2.5, step=0.01, value=None, format="%.2f")
    with col3:
        idade = st.number_input("Idade (anos):", min_value=2, max_value=120, step=1, value=None)

    if st.form_submit_button("Calcular IMC e Obter Orientações", type="primary"):
        if peso is None or altura is None or idade is None:
            st.error("Por favor, preencha todos os campos!")
        else:
            try:
                imc = calc.calcular_imc(peso, altura)
                classificacao, descricao, cor = calc.classificar_imc(imc)

                st.session_state.calculado = True

                st.success("Análise Completa Realizada!")

                with st.container():
                    col_res1, col_res2 = st.columns([1, 2])

                    with col_res1:
                        st.metric("IMC Calculado", f"{imc:.1f}")
                        st.markdown(f"""
                            **Classificação:**
                            :{cor}[**{classificacao}**]
                            _{descricao}_
                        """)
                        # O gráfico Plotly foi removido aqui.
                        st.info("O gráfico de IMC foi removido para evitar erros de dependência na publicação. Se desejar, podemos explorar outras opções de visualização.")

                    with col_res2:
                        st.markdown(calc.obter_dicas(classificacao, idade))

                        with st.expander("🔍 Referências Científicas", expanded=True):
                            st.markdown(calc.obter_resumos())

            except Exception as e:
                st.error(f"Erro: {str(e)}")

# --- Botão "Novo Cálculo" ---
if st.session_state.calculado:
    st.markdown("---")
    if st.button("Novo Cálculo de IMC", key="novo_calculo_button"):
        st.session_state.calculado = False
        st.experimental_rerun()

st.markdown("---")
st.markdown("""
    **Desenvolvido por:** Marcia Romanato
""")