# -*- coding: utf-8 -*-
"""26app_imc_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2i9xtRkVEHxG14BUPV5prNHSucgK2jJ
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go # Importar para criar o gráfico de medidor

class CalculadoraIMC:
    def __init__(self):
        self.classificacoes = [
            {"max": 18.4, "cat": "Abaixo do peso", "desc": "Indicado buscar orientação para ganho de peso saudável.", "cor": "warning"},
            {"max": 24.9, "cat": "Peso normal", "desc": "Seu peso está saudável. Mantenha hábitos equilibrados.", "cor": "success"},
            {"max": 29.9, "cat": "Sobrepeso", "desc": "Recomenda-se orientação para plano de emagrecimento.", "cor": "warning"},
            {"max": 34.9, "cat": "Obesidade Grau I", "desc": "Acompanhamento profissional importante.", "cor": "danger"},
            {"max": 39.9, "cat": "Obesidade Grau II", "desc": "Risco elevado. Procure ajuda urgente.", "cor": "danger"},
            {"max": float('inf'), "cat": "Obesidade Grau III", "desc": "Risco muito elevado. Tratamento rigoroso.", "cor": "danger"}
        ]

        # Dados para o gráfico de medidor, com valores min/max explícitos e cores hex
        # Cores ajustadas para melhor contraste e visualização no gauge
        self.plot_classificacoes = [
            {"min": 0, "max": 18.4, "cat": "Abaixo do peso", "color_code": "#FFC0CB"}, # Pink (mais suave que azul para "abaixo")
            {"min": 18.5, "max": 24.9, "cat": "Peso normal", "color_code": "#90EE90"}, # LightGreen
            {"min": 25.0, "max": 29.9, "cat": "Sobrepeso", "color_code": "#FFD700"}, # Gold (Amarelo/Laranja claro)
            {"min": 30.0, "max": 34.9, "cat": "Obesidade Grau I", "color_code": "#FF8C00"}, # DarkOrange
            {"min": 35.0, "max": 39.9, "cat": "Obesidade Grau II", "color_code": "#FF4500"}, # OrangeRed
            {"min": 40.0, "max": 60.0, "cat": "Obesidade Grau III", "color_code": "#B22222"}  # FireBrick (Vermelho mais escuro)
        ]

    def calcular_imc(self, peso, altura):
        if altura <= 0 or peso <= 0:
            raise ValueError("Valores devem ser positivos.")
        return peso / (altura ** 2)

    def classificar_imc(self, imc):
        for classe in self.classificacoes:
            if imc <= classe["max"]:
                return (classe["cat"], classe["desc"], classe["cor"])
        return self.classificacoes[-1]['cat'], self.classificacoes[-1]['desc'], self.classificacoes[-1]['cor']

    def obter_dicas(self, classificacao, idade):
        dicas = [
            "### Dicas Gerais para uma Alimentação Saudável", # Removido o emoji aqui para consistência com o expander
            "- **Priorize alimentos in natura ou minimamente processados:** Frutas, verduras, legumes, grãos inteiros, carnes magras, ovos.",
            "- **Evite alimentos ultraprocessados:** Refrigerantes, biscoitos recheados, salgadinhos, embutidos - ricos em açúcar, sódio e gorduras não saudáveis.",
            "- **Cozinhe seus próprios alimentos:** Controle os ingredientes e qualidade das preparações.",
            "- **Faça refeições conscientes:** Coma devagar, em ambiente tranquilo e preferencialmente em companhia.",
            "- **Hidrate-se adequadamente:** Beba água ao longo do dia (6-8 copos diários).",
            "- **Use óleos, sal e açúcar com moderação:** Prefira versões naturais e evite excessos.",
            "- **Mantenha-se ativo:** Combine alimentação saudável com atividade física regular.",
            "- **Varie os alimentos:** Consuma diferentes grupos alimentares ao longo da semana.",
            "- **Atenção aos rótulos:** Leia as informações nutricionais dos produtos industrializados."
        ]

        if "Abaixo do peso" in classificacao:
            dicas.extend([
                "\n#### Estratégias para Ganho de Peso Saudável - Recomendações Médicas de Preferência:", # Ajuste de header para sub-seção
                "- Consuma alimentos ricos em nutrientes e calorias saudáveis: abacate, azeite, castanhas",
                "- Faça 6 refeições diárias em porções menores",
                "- Inclua proteínas em todas as refeições principais",
                "- Consulte um nutricionista para plano individualizado"
            ])
        elif "Sobrepeso" in classificacao or "Obesidade" in classificacao:
            dicas.extend([
                "\n#### Estratégias para Emagrecimento Saudável - Recomendações Médicas de Preferência:", # Ajuste de header
                "- Aumente o consumo de fibras: vegetais folhosos, frutas com casca, grãos integrais",
                "- Consuma proteínas magras: peixes, frango, ovos, leguminosas",
                "- Reduza o consumo de bebidas alcoólicas",
                "- Consulte um nutricionista para plano individualizado",
                "- Reduza gradualmente o consumo de açúcares e gorduras saturadas",
                "- Mantenha regularidade nas refeições para evitar compulsões",
                "- Importante nesse processo - Pratique atividade física regular com orientação profissional"
            ])
        elif "Peso normal" in classificacao:
            dicas.extend([
                "\n#### Mantenha seus Hábitos Saudáveis:", # Ajuste de header
                "- Continue com a rotina alimentar equilibrada",
                "- Monitore seu peso periodicamente",
                "- Experimente novas receitas saudáveis",
                "- Importante nesse processo - Mantenha check-ups regulares"
            ])

        if idade < 18:
            dicas.extend([
                f"\n#### Considerações para {idade} anos:", # Ajuste de header
                "- Fundamental papel da família na oferta de alimentos saudáveis",
                "- Evite açúcar para menores de 2 anos e modere para maiores",
                "- Priorize lanches naturais: frutas, sanduíches integrais",
                "- Mantenha horários regulares para as refeições"
            ])
        elif idade >= 60:
            dicas.extend([
                f"\n#### Considerações para {idade} anos:", # Ajuste de header
                "- Aumente consumo de proteínas para manter massa muscular",
                "- Atenção à hidratação (a sede pode diminuir com a idade)",
                "- Consuma alimentos ricos em cálcio e vitamina D",
                "- Adapte textura dos alimentos se necessário"
            ])

        return "\n".join(dicas)

    def obter_resumos(self):
        return """
        ## 📚 Referências Científicas

        ### Guias Oficiais:
        1. [Guia Alimentar para a População Brasileira](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_populacao_brasileira_2ed.pdf)
        2. [Guia para Crianças Menores de 2 Anos](https://bvsms.saude.gov.br/bvs/publicacoes/guia_alimentar_crianca_brasileira_versao_resumida.pdf)

        ### Estudos Relevantes:
        3. [Alimentação Saudável](https://bvsms.saude.gov.br/bvs/publicacoes/alimentacao_saudavel.pdf)
        4. [Clínica Einstein: Dietas & Emagrecimento](https://vidasaudavel.einstein.br/wp-content/uploads/2021/02/98.-Dietas-Emagrecimento.pdf)
        """

# Configuração da Página
st.set_page_config(
    page_title="Orientações básicas",
    page_icon="🥗",
    layout="wide", # Mantido wide para aproveitar o espaço em telas maiores e Streamlit ajusta para menores
    initial_sidebar_state="expanded" # Mantido expandido, mas pode ser 'collapsed' para mobile se preferir
)

# Interface Principal
st.title("🥗 Calculadora de IMC")
st.markdown("""
    *Calculadora de IMC com orientações baseadas em evidências científicas:*
""")

# Inicializa a calculadora
calc = CalculadoraIMC()

# Inicializa o estado da sessão para os inputs, se ainda não existirem
if 'peso_input_value' not in st.session_state:
    st.session_state.peso_input_value = None
if 'altura_input_value' not in st.session_state:
    st.session_state.altura_input_value = None
if 'idade_input_value' not in st.session_state:
    st.session_state.idade_input_value = None
if 'show_results' not in st.session_state: # Novo estado para controlar a exibição dos resultados
    st.session_state.show_results = False

# Entradas do Usuário dentro de um formulário
with st.form(key='form_imc'):
    # Usar colunas para desktop, mas Streamlit as empilhará em dispositivos móveis
    col1, col2, col3 = st.columns(3)
    with col1:
        peso = st.number_input("Peso (kg):", min_value=30.0, max_value=300.0, step=0.1,
                               value=st.session_state.peso_input_value, format="%.1f", key="peso_input",
                               help="Insira seu peso em quilogramas (ex: 70.5)")
    with col2:
        altura = st.number_input("Altura (m):", min_value=1.0, max_value=2.5, step=0.01,
                                 value=st.session_state.altura_input_value, format="%.2f", key="altura_input",
                                 help="Insira sua altura em metros (ex: 1.75)")
    with col3:
        idade = st.number_input("Idade (anos):", min_value=2, max_value=120, step=1,
                                value=st.session_state.idade_input_value, key="idade_input",
                                help="Insira sua idade em anos")

    if st.form_submit_button("Calcular IMC e Obter Orientações", type="primary"):
        if peso is None or altura is None or idade is None:
            st.error("Por favor, preencha todos os campos!")
            st.session_state.show_results = False
        else:
            try:
                imc = calc.calcular_imc(peso, altura)
                classificacao, descricao, cor = calc.classificar_imc(imc)

                st.session_state.imc_resultado = imc
                st.session_state.classificacao_resultado = classificacao
                st.session_state.descricao_resultado = descricao
                st.session_state.cor_resultado = cor
                st.session_state.dicas_resultado = calc.obter_dicas(classificacao, idade)
                st.session_state.resumos_resultado = calc.obter_resumos()
                st.session_state.show_results = True

            except Exception as e:
                st.error(f"Erro: {str(e)}")
                st.session_state.show_results = False

# --- Exibição dos Resultados (fora do formulário) ---
if st.session_state.show_results:
    st.success("Análise Completa Realizada!")

    # Usa um container para o IMC e o gráfico, e outro para as dicas e referências
    # Em telas pequenas, as colunas vão se empilhar automaticamente.
    col_res1, col_res2 = st.columns([1, 2])

    with col_res1:
        st.metric("IMC Calculado", f"{st.session_state.imc_resultado:.1f}")
        st.markdown(f"""
            **Classificação:**
            :{st.session_state.cor_resultado}[**{st.session_state.classificacao_resultado}**]
            _{st.session_state.descricao_resultado}_
        """)

        st.markdown("---")

        st.subheader("📊 Classificação do IMC")

        gauge_steps = []
        for item in calc.plot_classificacoes:
            gauge_steps.append(
                dict(range=[item["min"], item["max"]], color=item["color_code"], name=item["cat"])
            )

        fig = go.Figure(go.Indicator(
            mode="gauge+number", # Removido 'delta' para simplificar e focar na posição atual
            value=st.session_state.imc_resultado,
            gauge={
                'axis': {'range': [0, 60], 'tickvals': [0, 18.5, 25, 30, 35, 40, 60],
                         'ticktext': ['0', '18.5', '25', '30', '35', '40+'], 'visible': True},
                'bar': {'color': "darkblue"},
                'steps': gauge_steps,
                'threshold': {
                    'line': {'color': "red", 'width': 4},
                    'thickness': 0.75,
                    'value': st.session_state.imc_resultado}
            },
            domain={'x': [0, 1], 'y': [0, 1]}
        ))

        fig.update_layout(
            title_text="Seu IMC na Escala de Classificação",
            height=300, # Altura fixa, mas Plotly é responsivo na largura
            margin=dict(l=20, r=20, t=50, b=20),
            title_font_size=16 # Ajustado para melhor legibilidade em telas menores
        )

        st.plotly_chart(fig, use_container_width=True)


    with col_res2:
        # Colocando as dicas dentro de um expander para melhor visualização em celular
        with st.expander("📌 Dicas de Alimentação e Saúde", expanded=True): # Expandido por padrão
            st.markdown(st.session_state.dicas_resultado)

        with st.expander("🔍 Referências Científicas", expanded=False): # Começa recolhido
            st.markdown(st.session_state.resumos_resultado)

    st.markdown("---")

    if st.button("Novo Cálculo de IMC", key="novo_calculo_button"):
        st.session_state.peso_input_value = None
        st.session_state.altura_input_value = None
        st.session_state.idade_input_value = None
        st.session_state.show_results = False
        st.rerun() # Adicionado st.rerun() para recarregar o app e limpar completamente os campos

st.markdown("---")
st.markdown("""
    **Desenvolvido por:** Marcia Romanato
""")